[package]
name = "fileserve"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = {path = "../shared"}
serde = { version = "1.0.214", features = ["derive"] }
serde_json = "1.0.132"
sqlite = "0.36.1"
tiny_http = "0.12.0"
url = "2.5.4"

