[package]
name = "fswatch"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = { version = "6.1.1", features = ["serde"] }
sqlite = "0.36.1"
fileserve = {path = "../fileserve"}
shared = {path = "../shared"}
highway = "1.2.0"
